# Generated by Django 2.0.5 on 2018-07-24 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0002_auto_20180722_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 6, 30, 53, tzinfo=utc)),
        ),
    ]
