# Generated by Django 2.0.5 on 2018-07-27 06:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0003_auto_20180724_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 27, 6, 19, 30, tzinfo=utc)),
        ),
    ]
