# Generated by Django 2.0.5 on 2018-08-01 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0005_auto_20180727_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='users',
        ),
        migrations.AddField(
            model_name='followers',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 16, 22, 13, tzinfo=utc)),
        ),
    ]
