# Generated by Django 2.0.5 on 2018-08-01 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0006_auto_20180801_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 18, 28, 32, tzinfo=utc)),
        ),
    ]
