# Generated by Django 2.0.5 on 2018-08-01 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0007_auto_20180801_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='documents/default.jpg', null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 18, 31, 44, tzinfo=utc)),
        ),
    ]
