# Generated by Django 2.0.5 on 2018-08-01 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import twitterapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0008_auto_20180802_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='documents/default.jpg', upload_to=twitterapp.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 18, 46, 17, tzinfo=utc)),
        ),
    ]
